export const FETCH_AUDIO_START = "FETCH_AUDIO_START";
export const FETCH_AUDIO_SUCCESS = "FETCH_AUDIO_SUCCESS";
export const FETCH_AUDIO_FAILURE = "FETCH_AUDIO_FAILURE";
export const FETCH_AUDIO_SPECIFIC = "FETCH_AUDIO_SPECIFIC";
export const FETCH_AUDIO_SPECIFIC_SUCCESS = "FETCH_AUDIO_SPECIFIC_SUCCESS";
export const FETCH_AUDIO_SPECIFIC_FAILURE = "FETCH_AUDIO_SPECIFIC_FAILURE";
